//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Obvious.Soap.ScriptableEventVector2))]
	public class PropertyProvider_Obvious_Soap_ScriptableEventVector2 : Unity.VisualScripting.SerializedPropertyProvider<Obvious.Soap.ScriptableEventVector2>
	{
	}
}
